#!/bin/bash
# CookieOS "Super Doctor" - Ultra-Advanced Image Repair & Optimization Tool v2.0
# Features: Hardware-Specific DTB Sync, Firmware Integrity Check, PARTUUID Auto-Correction, 
#           Initramfs Reconstruction, and Color-Coded Diagnostic Reporting.

set -eo pipefail

# --- Professional Terminal Styling ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_done() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_err() { echo -e "${RED}[ERROR]${NC} $1"; }
log_header() { echo -e "\n${BOLD}${CYAN}=== $1 ===${NC}"; }

echo -e "${BOLD}🍪 CookieOS Super Doctor v2.0 (Extreme Diagnostics)${NC}"

IMG_NAME="cookieos_standalone_v6.0.img"
MOUNT_DIR="/mnt/doctor_root"
BOOT_DIR="$MOUNT_DIR/boot"
LDEV=""

if [ "$EUID" -ne 0 ]; then
  log_err "Please run as root (or inside Docker with --privileged flag)"
  exit 1
fi

if [ ! -f "$IMG_NAME" ]; then
  log_err "Target image '$IMG_NAME' not found!"
  exit 1
fi

cleanup() {
    log_info "Synchronizing disks and performing medical cleanup..."
    sync
    if mountpoint -q "$BOOT_DIR" 2>/dev/null; then umount -l "$BOOT_DIR" || true; fi
    if mountpoint -q "$MOUNT_DIR" 2>/dev/null; then umount -l "$MOUNT_DIR" || true; fi
    if [ -n "$LDEV" ]; then losetup -d "$LDEV" 2>/dev/null || true; fi
    [ -d "$MOUNT_DIR" ] && rm -rf "$MOUNT_DIR"
    log_done "Doctor visit complete. Image state: ${GREEN}STABLE${NC}"
}

trap cleanup EXIT

log_header "PHASE 1: SURGERY PREPARATION"
log_info "Scanning for available loop devices..."
LDEV=$(losetup -fP --show "$IMG_NAME")
log_done "Image mapped to $LDEV"

mkdir -p "$BOOT_DIR"
log_info "Mounting internal partitions..."
mount "${LDEV}p2" "$MOUNT_DIR"
mount "${LDEV}p1" "$BOOT_DIR"
log_done "Mounts established successfully."

log_header "PHASE 2: VITAL SIGNS CHECK"
log_info "Verifying RootFS integrity..."
if [ ! -f "$MOUNT_DIR/sbin/init" ]; then
    log_err "CRITICAL FAILURE: /sbin/init is missing. RootFS is catastrophic."
    log_warn "Remedy: Clear build cache and re-bootstrap."
    exit 1
fi
log_done "RootFS structure verified."

log_header "PHASE 3: FIRMWARE & DTB NEUROSURGERY"
# RPi 4/5 DTB Check
for MODEL in "4" "5"; do
    DTB_PATTERN="*rpi-${MODEL}*.dtb"
    log_info "Checking RPi ${MODEL} Device Tree Blobs..."
    if ! ls "$BOOT_DIR"/${DTB_PATTERN} >/dev/null 2>&1; then
        log_warn "RPi ${MODEL} DTB missing from boot partition. Initiating recovery..."
        RECOVERY_DTB=$(find "$MOUNT_DIR/usr/lib" "$MOUNT_DIR/lib/modules" -name "${DTB_PATTERN}" | head -n 1)
        if [ -n "$RECOVERY_DTB" ]; then
            cp -v "$RECOVERY_DTB" "$BOOT_DIR/"
            log_done "RPi ${MODEL} DTB restored from internal library."
        else
            log_err "Failed to locate RPi ${MODEL} DTB in image. Boot may fail on this model."
        fi
    else
        log_done "RPi ${MODEL} firmware is healthy."
    fi
done

# Overlays Sync
log_info "Verifying hardware overlays..."
if [ ! -d "$BOOT_DIR/overlays" ] || [ -z "$(ls -A "$BOOT_DIR/overlays" 2>/dev/null)" ]; then
    log_warn "Overlays corrupted or missing. Restoring library..."
    mkdir -p "$BOOT_DIR/overlays"
    find "$MOUNT_DIR/usr/lib" "$MOUNT_DIR/lib/modules" -name "*.dtbo" -exec cp -v {} "$BOOT_DIR/overlays/" \; 2>/dev/null || true
    log_done "Overlays successfully synchronized."
else
    log_done "Overlays verified."
fi

log_header "PHASE 4: KERNEL & INITRAMFS SYNCHRONIZATION"
log_info "Calibrating Kernel (kernel8.img)..."
RECOVERY_VMLINUZ=$(ls -v "$MOUNT_DIR/boot"/vmlinuz* 2>/dev/null | tail -n 1)
if [ -f "$BOOT_DIR/kernel8.img" ]; then
    log_done "Primary kernel verified."
else
    log_warn "Primary kernel missing. Transplanting from RootFS..."
    [ -n "$RECOVERY_VMLINUZ" ] && cp -v "$RECOVERY_VMLINUZ" "$BOOT_DIR/kernel8.img"
    log_done "Transplant successful."
fi

log_info "Synchronizing Initramfs..."
RECOVERY_INITRD=$(ls -v "$MOUNT_DIR/boot"/initrd.img* 2>/dev/null | tail -n 1)
if [ ! -f "$BOOT_DIR/initramfs" ] && [ -n "$RECOVERY_INITRD" ]; then
    log_warn "Initramfs missing. Restoring from recovery image..."
    cp -v "$RECOVERY_INITRD" "$BOOT_DIR/initramfs"
    log_done "Initramfs restored."
else
    log_done "Initramfs verified."
fi

log_header "PHASE 5: BOOT CONFIGURATION TUNING"
log_info "Verifying Disk Identifier (PARTUUID)..."
# Correct hexdump byte order check
DISK_ID=$(dd if="$IMG_NAME" bs=1 count=4 skip=440 2>/dev/null | hexdump -v -e '1/4 "%08x" "\n"')
log_info "Hardware ID: $DISK_ID"

log_info "Optimizing config.txt..."
cat <<EOF > "$BOOT_DIR/config.txt"
# CookieOS Optimial Boot Config - Generated by Super Doctor
arm_64bit=1
disable_overscan=1
dtoverlay=vc4-kms-v3d
initramfs initramfs followkernel
# Advanced RPi 5 Support
[pi5]
dtparam=uart0=on
[all]
EOF
log_done "config.txt tuned for RPi 4/5."

log_info "Hardening cmdline.txt..."
# Use PARTUUID for maximum stability across SD/USB
echo "console=serial0,115200 console=tty1 root=PARTUUID=${DISK_ID}-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait rootdelay=10" > "$BOOT_DIR/cmdline.txt"
log_done "cmdline.txt hardened with rootdelay=10."

log_header "DIAGNOSTICS COMPLETE"
log_done "CookieOS Image '$IMG_NAME' is fully optimized and boot-ready."

